### ISSUE TITLE
想请教一下使用emlo的原因？

### ISSUE THREAD

**Issue by yzho0907** [sys1874/Seq2seq-for-Souhu-2019#1]
请问下大佬结合emlo的原因，还有以生成的方式来代替直接的分类取得很不错的结果的理论，谢谢。或者有你们有参考哪些论文嘛？

**Comment by sys1874** [comment]
1. 结合elmo 是因为 核心实体大部分是低频单词，elmo 编码包含了 lstm上下文+char cnn 这样可以在一定程度上缓解OOV问题。
2. 本质上，该模型也是一个序列标注模型（我们用attention分布对输入文档进行核心实体标注）。 只是通过decoder，可以使得被标注的核心实体之间，产生了关联。
3. 参考论文，暂时没有，模型拍脑袋想的。。。

**Comment by yzho0907** [comment]
@sys1874 谢谢
